config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'marvel_api_auth#index'
  post   '/login',      to: 'marvel_api_auth#create'
  delete '/logout',     to: 'marvel_api_auth#destroy'
  get    '/signup',     to: 'users#new'

  resources :users,           only: [:create, :show, :new]
  resources :characters,      only: [:index] do
    resources :comics,        only: [:index]
  end
  resources :comics, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates_uniqueness_of :marvel_id

  has_many :characters_comics
  has_many :comics, through: :characters_comics
end

app/models/characters_comic.rb
class CharactersComic < ApplicationRecord
  belongs_to :character, dependent: :destroy
  belongs_to :comic, dependent: :destroy

  validates :character, presence: true
  validates :comic, presence: true
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :characters_comics
  has_many :comics, through: :characters_comics
end

app/models/user.rb
class User < ApplicationRecord
  validates :api_key, :priv_key, presence: true
  validates :api_key, :priv_key, uniqueness: true
  validates :api_key, length: { in: 32..32 }
  validates :priv_key, length: { in: 40..40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    all_characters.empty? ? fetch_characters : all_characters
    @characters = paginate
  end

  private

  def all_characters
    Character.all
  end

  def paginate
    Kaminari.paginate_array(all_characters).page(params[:page]).per(10)
  end

  def fetch_characters
    marvel_api = MarvelApi.new(api_key: current_user.api_key, priv_key: current_user.priv_key)
    heroes = marvel_api.all_characters
    RecordHeroes.call(heroes)
  end

  def character_params
    params.permit(:api_key, :priv_key)
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    all_comics.empty? ? fetch_comics : all_comics
  end

  private

  def all_comics
    @comics = set_heroe.characters_comics.all
  end

  def fetch_comics
    marvel_api = MarvelApi.new(api_key: current_user.api_key, priv_key: current_user.priv_key)
    heroe_comics = marvel_api.heroe_comics(marvel_id: set_heroe.marvel_id)
    comic = RecordComics.new(character_id: set_heroe.id)
    comic.call(heroe_comics)
  end

  def set_heroe
    @heroe = Character.find(params[:character_id])
  end
end

app/controllers/marvel_api_auth_controller.rb
class MarvelApiAuthController < ApplicationController
  def index; end

  def create
    @user = finduser_by_apikey
    if @user && validate_private_key
      LogIn.call(@user, session)
      redirect_to characters_path
    else
      flash.now[:danger] = 'API key / Private key incorrect or not found'
      render 'index'
    end
  end

  private

  def finduser_by_apikey
    User.find_by(api_key: params[:marvel_api_auth][:api_key])
  end

  def validate_private_key
    @user.priv_key == params[:marvel_api_auth][:priv_key]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        LogIn.call(@user, session)
        format.html { redirect_to characters_path, notice: 'NOW! You are one of our Heroes' }
        format.json { render json: @user }
      else
        format.html { render 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:api_key, :priv_key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/marvel_api_auth_helper.rb
module MarvelApiAuthHelper
end

app/views/characters/index.html.erb
<% # TODO: Implement Decorators and remove logic from View %>
<%= render 'layouts/header' %>
<div class="container-fluid aligned">

  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

    <div class="card card-outline-primary text-xs-center">
        <div class="card-block">

            <table class="table table-inverse">
                <thead class="thead-default">
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Last updated</th>
                    </tr>
                </thead>
                <tbody>
                    <% @characters.each do |model| %>
                    <tr>
                        <td class='text-left'>
                          <%= image_tag("#{model.thumbnail}.jpg", size: "100x100", alt: "Heroe pic") %>
                        </td>
                        <td class='text-left'><%= link_to model.name, character_comics_path(model.id) %></td>
                        <td class='text-left'><%= model.description %></td>
                        <td><%= model.updated_at %></td>
                        <% end %>
                    </tr>
                </tbody>

                <%= paginate @characters %>
            </table>
            <%= paginate @characters %>
        </div>
    </div>
</div>

app/views/comics/index.html.erb
<% # TODO: Implement Decorators and remove logic from View %>
<% # TODO: Fix a bug, when clicking in some Heroes, exception is displayed %>
<%= render 'layouts/header' %>
<div class="container-fluid aligned">
    <div style='margin-bottom: 50px;'>
        <%= link_to "Back", request.referer.present? ? request.referer : characters_path , class: "btn btn-primary" %>
    </div>
    <div class='container'>
        <div class="row">
            <div class="col-sm-8">
                <div class='card'>
                    <h3 class="card-header">Character card</h3>
                    <% # TODO: The image extension should be captured from the API returned data, for this moment, adding the hard-coded extension is the best option %>
                    <%= image_tag("#{@comics.first.character.thumbnail}.jpg", size: "200x200", alt: "Heroe card cap", class: 'card-img-top') %>
                    <div class='card-block'>
                        <h4 class='card-title'><%= @comics.first.character.name %></h4>
                        <p class='card-text'><%= @comics.first.character.description %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <%= @comics.map do |character_comics| %>
    <div class='container'>
        <div class='row'>
            <div class="col-md-16">
                <div class="card">
                  <% # TODO: Reorder Issue Number to ASC %>
                    <h3 class="card-header">Comic Issue #<%= character_comics.comic.issue_number.to_i %></h3>
                    <% # TODO: The image extension should be captured from the API returned data, for this moment, adding the hard-coded extension is the best option %>
                    <% # TODO: Improve adjustament for mobile %>
                    <div class="row">
                      <div class="col-md-4 col-xs-1"><%= image_tag("#{character_comics.comic.thumbnail}.jpg", size: '450x582', alt: 'Comic cover') %></div>
                      <h4 class="card-title text-xs-right col-xs-14 col-md-7"><%= character_comics.comic.title %></h4>
                      <div class="row">
                      <div class='card-block' style="width: 90rem;">
                        <p class='card-text text-xs-left col-xs-1 col-md-6' style="margin-left: 70px;"><%= character_comics.comic.description %></p>
                      </div>
                    </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark navbar-fixed-top" style="background-color:#563d7c">
  <div class='nav navbar-nav pull-xs-left'>
    <%= image_tag "dp", class: 'navbar-brand' %>
    <%= link_to 'Home', root_path, class: 'nav-item nav-link' %>
  </div>
</nav>

app/views/layouts/_user_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
     <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DpMarvel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marvel_api_auth/index.html.erb
<%= image_tag "banner_marvel_topo", class: 'banner img-fluid' %>
<br/>
<div class="container">
    <h2 class="form-signin-heading">Log in</h2>
    <% if flash[:danger] %>
      <div class="alert alert-danger"><%= flash[:danger] %></div>
    <% end %>
    <%= form_for :marvel_api_auth, url: login_path do |f| %>
        <%= f.label :api_key %>
        <%= f.text_field :api_key, placeholder: "Marvel's API Key", required: true, autofocus: true, autocomplete: true, class: 'form-control' %>
        <br/>
        <%= f.label :private_key %>
        <%= f.password_field :priv_key, placeholder: "Marvel's Private Key", autocomplete: false, required: true, class: 'form-control' %>
        <%= submit_tag 'Sign in', class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
    <h6>
        <%= link_to 'Do not have an account, click here!', signup_path  %>
    </h6>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>
<div class="container aligned">
  <h1 class="form-signin-heading">Sign Up</h1>
    <h2 class="form-signin-heading">Please enter your keys</h2>
    <%= form_for @user do |f| %>
        <%= render 'layouts/user_errors' %>
        <%= f.label :api_key %>
        <%= f.text_field :api_key, placeholder: "Marvel's API Key", required: true, autofocus: true, autocomplete: true, class: 'form-control' %>
        <br/>
        <%= f.label :private_key %>
        <%= f.password_field :priv_key, placeholder: "Marvel's Private Key", autocomplete: false, required: true, class: 'form-control' %>
        <%= submit_tag 'Submit', class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
    <h6>
        <%= link_to 'Do not have keys, click here!', 'http://developer.marvel.com'  %>
    </h6>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/header' %>
<div class="container-fluid aligned">
  <%= link_to "Back", root_path, class: "btn btn-secondary" %>

    <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <div class="card card-outline-primary text-xs-center">
        <div class="card-block">

            <table class="table table-inverse">
                <thead class="thead-default">
                    <tr>
                        <th>API Key</th>
                        <th>Private Key</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class='text-left'><%= @user.api_key %></td>
                        <td class='text-left'><%= @user.priv_key %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>